services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "HmDevices"
      POSTGRES_USER: "superuser"
      POSTGRES_PASSWORD: "47QUv7J6bR31"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5445:5432
volumes:
  postgres-data:  